### PR TITLE
Update Github Action

### PR DESCRIPTION
**Pull request by joelmathewphilip**
Add trigger to trigger the workflow manually for testing

### CODE REVIEW

**Comment by rohan472000** [comment]
its failing, kindly check.

**Comment by joelmathewphilip** [comment]
Please review and approve

**Comment by rohan472000** [comment]
Really, you just removed PR branch on main from yml, so it worked otherwise it will still fail.

Take your time and fix it.

**Comment by joelmathewphilip** [comment]
I removed the PR trigger because the workflow tries to merge changes to the running branch. Since the workflow is running on your repo, it will not recognise my main branch and hence gives the error. Ideally this workflow should run only during pushes to main or a cron job.

**Comment by rohan472000** [comment]
Ahh..let's try this then on main.

**Review by rohan472000 — APPROVED** [review]

**Pull request merged**
